runArea("clock", runClockTests)
runArea("models", runModelsTests)
runArea("rule matcher", runRuleMatcherTests)
runArea("engine decisions", runEngineDecisionTests)
runArea("engine rules", runEngineRuleTests)
runArea("engine sessions", runEngineSessionTests)
runArea("engine schedules", runEngineScheduleTests)
runArea("engine windows", runEngineWindowTests)
runArea("block end", runBlockEndTests)
runArea("dated block", runDatedBlockTests)
runArea("time window path", runTimeWindowPathTests)
runArea("week coverage", runWeekCoverageTests)
runArea("rollover end", runRolloverEndTests)
runArea("engine clock jumps", runEngineClockJumpTests)
runArea("engine clock tampering", runEngineClockTamperTests)
runArea("engine streak", runEngineStreakTests)
runArea("engine usage", runEngineUsageTests)
runArea("engine relief", runEngineReliefTests)
runArea("engine groups", runEngineGroupTests)
runArea("store", runStoreTests)
runArea("store format", runStoreFormatTests)
runArea("store schema", runStoreSchemaTests)
runArea("config builder", runConfigBuilderTests)
runArea("group order", runGroupOrderTests)
runArea("group copies", runGroupCopyTests)
runArea("all groups switch", runAllGroupsSwitchTests)
runArea("target picker", runTargetPickerTests)
runArea("target sheets", runTargetSheetTests)
runArea("control rules", runControlRulesTests)
runArea("preset choices", runPresetChoiceTests)
runArea("group summary", runGroupSummaryTests)
runArea("editor freeze", runEditorFreezeTests)
runArea("editor state", runEditorStateTests)
runArea("editor cards", runEditorCardsTests)
runArea("app state", runAppStateTests)
runArea("app state sessions", runAppStateSessionTests)
runArea("app state web", runAppStateWebTests)
runArea("app state usage", runAppStateUsageTests)
runArea("pause friction", runPauseFrictionTests)
runArea("break wait", runBreakWaitTests)
runArea("quit policy", runQuitPolicyTests)
runArea("activation guards", runActivationGuardTests)
runArea("pause screen model", runPauseScreenModelTests)
runArea("hide ladder", runHideLadderTests)
runArea("hide sweep", runHideSweepTests)
runArea("fullscreen escalation", runFullscreenEscalationTests)
runArea("blunt block", runBluntBlockTests)
runArea("categories", runCategoryTests)
runArea("browser watch", runBrowserWatchTests)
runArea("block page", runBlockPageTests)
runArea("earned opens", runEarnedOpenTests)
runArea("browser history", runBrowserHistoryTests)
runArea("settings lock", runSettingsLockTests)
runArea("settings lock in the app", runSettingsLockEditTests)
runArea("settings door", runSettingsDoorTests)
runArea("edit direction", runEditDirectionTests)
runArea("group locks", runGroupLockTests)
runArea("group locks in the app", runGroupLockEditTests)
runArea("group lock escapes", runGroupLockEscapeTests)
runArea("dated block in the app", runDatedBlockEditTests)
runArea("undo lock", runUndoLockTests)
runArea("quick disable lock", runQuickDisableLockTests)
runArea("keep-alive seed", runKeepAliveSeedTests)
runArea("launch agent", runLaunchAgentTests)
runArea("legacy migration", runLegacyMigrationTests)

finishTests()
